import Game.Levels.CountCharAndElemOf.L01_CountCharInAppend
import Game.Levels.CountCharAndElemOf.L02_CountCharInReplicateChar
import Game.Levels.CountCharAndElemOf.L03_CharInAppendLeft
import Game.Levels.CountCharAndElemOf.L04_CharInAppendRight
import Game.Levels.CountCharAndElemOf.L05_CharInReplicateChar

World "CountCharAndElemOf"
Title "CountChar and ElemOf"

Introduction "Welcome to **The CountChar and ElemOf World**!

In this world, you will study the behavior of the functions ```countCharInWord``` and ```elemOf```
in combination with the functions ```append``` and ```replicateChar```:
- ```countCharInWord``` returns the number of occurrences of a given character in a word.
- ```elemOf``` determines whether a character is in a word or not. ```elemOf char word``` can
also be written as ```char ∈w word``` and the property holds if and only if the given character
appears in that word at least once.

You will first prove that counting the occurrences of a character in word generated by the append
function preserves the counts from individual words and sums them up.
You will then analyze how character counting behaves in words formed by repeating a single character.

Following this, you will establish that character membership is preserved under appending, both when a
character appears in the left word and when it appears in the right word.
Finally, you will prove that character membership is also preserved for character replicas.

Let's get started!
"

